// Extracts PROPS + DISCIPLINES from the two prototype HTMLs and emits:
//   _input/extracted.json          (ground-truth data for inspection)
//   supabase/seed/0001_permits_seed.sql  (idempotent seed: properties/disciplines/comments)
//
// Deterministic UUIDv5 ids make the seed safe to re-run (ON CONFLICT DO NOTHING).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");

// ---- deterministic UUIDv5 -------------------------------------------------
const NS = "1b3a6b00-0000-4000-8000-000000000001"; // fixed project namespace
function uuid5(name) {
  const ns = Buffer.from(NS.replace(/-/g, ""), "hex");
  const h = createHash("sha1").update(ns).update(name, "utf8").digest();
  const b = h.subarray(0, 16);
  b[6] = (b[6] & 0x0f) | 0x50;
  b[8] = (b[8] & 0x3f) | 0x80;
  const x = b.toString("hex");
  return `${x.slice(0, 8)}-${x.slice(8, 12)}-${x.slice(12, 16)}-${x.slice(16, 20)}-${x.slice(20, 32)}`;
}

// ---- balanced-delimiter literal extractor (string-aware) ------------------
function extractLiteral(src, marker) {
  const i = src.indexOf(marker);
  if (i < 0) throw new Error("marker not found: " + marker);
  let j = i + marker.length;
  while (j < src.length && src[j] !== "[" && src[j] !== "{") j++;
  const open = src[j];
  const close = open === "[" ? "]" : "}";
  let depth = 0, inStr = null, esc = false;
  for (let k = j; k < src.length; k++) {
    const c = src[k];
    if (inStr) {
      if (esc) esc = false;
      else if (c === "\\") esc = true;
      else if (c === inStr) inStr = null;
      continue;
    }
    if (c === "'" || c === '"' || c === "`") { inStr = c; continue; }
    if (c === open) depth++;
    else if (c === close && --depth === 0) return src.slice(j, k + 1);
  }
  throw new Error("unbalanced literal for " + marker);
}
function evalLiteral(lit) {
  return new Function("return (" + lit + ");")();
}

// ---- field mappers --------------------------------------------------------
const parseCycle = (s) => {
  const m = /Cycle\s+(\d+)/i.exec(s || "");
  return m ? parseInt(m[1], 10) : null;
};
const parseWorkflow = (s) => {
  const m = /^(\d{2})\/(\d{2})\/(\d{4})$/.exec((s || "").trim());
  return m ? `${m[3]}-${m[1]}-${m[2]}` : null;
};
const clean = (s) => (s === "—" || s === "" || s == null ? null : s);
const CS_MAP = {
  Unresolved: "UNRESOLVED",
  Resolved: "RESOLVED",
  "Info Only": "INFO_ONLY",
  Information: "INFO_ONLY",
};
function mapCommentStatus(cs) {
  const v = CS_MAP[(cs || "").trim()];
  if (!v) throw new Error("unknown comment cs: " + JSON.stringify(cs));
  return v;
}
function permitType(portfolio, key, addr) {
  if (/demo/i.test(addr) || key === "demo") return "demo";
  if (portfolio === "casas" && key === "3201") return "master";
  return "main";
}

// ---- process one file -----------------------------------------------------
function processFile(file, portfolio) {
  const src = readFileSync(join(HERE, file), "utf8");
  const PROPS = evalLiteral(extractLiteral(src, "const PROPS"));
  const DISCIPLINES = evalLiteral(extractLiteral(src, "const DISCIPLINES"));

  const properties = PROPS.map((p) => {
    const id = uuid5(`prop:${portfolio}:${p.addr}`);
    const disciplines = (DISCIPLINES[p.key] || []).map((d) => {
      const did = uuid5(`disc:${id}:${d.code}`);
      const comments = (d.comments || []).map((c) => ({
        id: uuid5(`cmt:${did}:${c.ref}`),
        ref_number: c.ref ?? null,
        text: c.text ?? null,
        city_status: mapCommentStatus(c.cs),
      }));
      return {
        id: did,
        code: d.code,
        name: d.name ?? null,
        reviewer_name: d.reviewer ?? null,
        city_status: d.cityStatus ?? null,
        total_comments: d.total ?? 0,
        open_comments: d.open ?? 0,
        info_comments: d.info ?? 0,
        comments,
      };
    });
    return {
      id,
      portfolio,
      address: p.addr,
      permit_number: clean(p.permit),
      permit_type: permitType(portfolio, p.key, p.addr),
      cycle: parseCycle(p.cycle),
      workflow_started: parseWorkflow(p.workflow),
      status_note: clean(p.note),
      disciplines,
    };
  });
  return properties;
}

const all = [
  ...processFile("PermitTracker_PortlandSaxum_v4.html", "portland_saxum"),
  ...processFile("PermitTracker_Casas_v3.html", "casas"),
];

// ---- SQL generation -------------------------------------------------------
const q = (s) => (s == null ? "NULL" : `'${String(s).replace(/'/g, "''")}'`);
const qi = (n) => (n == null || n === "" || Number.isNaN(n) ? "NULL" : String(n));

const lines = [];
lines.push("-- AUTO-GENERATED by _input/extract.mjs — do not edit by hand.");
lines.push("-- Seed: properties, disciplines, comments (verbatim iBuild text).");
lines.push("-- Idempotent: deterministic ids + ON CONFLICT DO NOTHING.");
lines.push("begin;");
lines.push("");

for (const p of all) {
  lines.push(
    `insert into properties (id, portfolio, address, permit_number, permit_type, cycle, workflow_started, status_note) values (${q(p.id)}, ${q(p.portfolio)}, ${q(p.address)}, ${q(p.permit_number)}, ${q(p.permit_type)}, ${qi(p.cycle)}, ${p.workflow_started ? q(p.workflow_started) : "NULL"}, ${q(p.status_note)}) on conflict (id) do nothing;`,
  );
  for (const d of p.disciplines) {
    lines.push(
      `insert into disciplines (id, property_id, code, name, reviewer_name, city_status, total_comments, open_comments, info_comments) values (${q(d.id)}, ${q(p.id)}, ${q(d.code)}, ${q(d.name)}, ${q(d.reviewer_name)}, ${q(d.city_status)}, ${qi(d.total_comments)}, ${qi(d.open_comments)}, ${qi(d.info_comments)}) on conflict (property_id, code) do nothing;`,
    );
    for (const c of d.comments) {
      lines.push(
        `insert into comments (id, discipline_id, ref_number, text, city_status) values (${q(c.id)}, ${q(d.id)}, ${qi(c.ref_number)}, ${q(c.text)}, ${q(c.city_status)}) on conflict (discipline_id, ref_number) do nothing;`,
      );
    }
  }
  lines.push("");
}
lines.push("commit;");

mkdirSync(join(ROOT, "supabase", "seed"), { recursive: true });
writeFileSync(join(ROOT, "supabase", "seed", "0001_permits_seed.sql"), lines.join("\n"), "utf8");
writeFileSync(join(HERE, "extracted.json"), JSON.stringify(all, null, 2), "utf8");

// ---- summary + validation -------------------------------------------------
let nProp = all.length, nDisc = 0, nCmt = 0;
const perProp = [];
for (const p of all) {
  let pd = 0, pc = 0;
  for (const d of p.disciplines) { pd++; pc += d.comments.length; }
  nDisc += pd; nCmt += pc;
  perProp.push(
    `  ${p.portfolio.padEnd(15)} ${p.address.padEnd(22)} cyc=${String(p.cycle ?? "-").padEnd(2)} disc=${String(pd).padStart(2)} comments=${String(pc).padStart(3)}`,
  );
}
console.log(perProp.join("\n"));
console.log(`\nTOTAL  properties=${nProp}  disciplines=${nDisc}  comments=${nCmt}`);
